ecotest/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls' ,namespace='product')),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name='product'

urlpatterns=[
    path('',views.index, name='Home'),
    path('<int:id>',views.product_detial,name='products_details' ),
    path('done_email/',views.doneemail, name='done_email'),
    path('done',views.done, name='done'),
    path('shoes/',views.shoes,name='shoes'),
    path('pants/',views.pants,name='pants'),
    path('tshirt/',views.tshirt,name='tshirt'),
    path('cartinfo/', views.product_detialbycart ,name='cartinfo'),
    path('productcart/',views.productcart , name='productcart'),
]

products/models.py
from django.db import models

# Create your models here.
class Products(models.Model):
    categorie = models.CharField(max_length=50, blank=True, null=True)
    clasement = models.IntegerField(blank=True,null=True)
    name = models.CharField(max_length=50)
    content = models.TextField()
    made = models.CharField(max_length=100)
    price = models.IntegerField()
    notprice=models.IntegerField()
    size=models.CharField(max_length=60, blank=True , null=True)
    image=models.ImageField(null=True, blank=True ,upload_to='photo/%y/%m/%d')
    image1=models.ImageField(null=True, blank=True ,upload_to='photo/%y/%m/%d')
    image2=models.ImageField(null=True, blank=True, upload_to='photo/%y/%m/%d')
    image3=models.ImageField(null=True, blank=True,upload_to='photo/%y/%m/%d')
    image4=models.ImageField(null=True, blank=True,upload_to='photo/%y/%m/%d')
    image5=models.ImageField(null=True, blank=True,upload_to='photo/%y/%m/%d')

    def __str__(self):
       return self.name    
    
class Customer_info(models.Model):
      quantity = models.IntegerField(null=True,blank=True)
      full_name= models.CharField(max_length=30 ,null=True,blank=True)
      city = models.CharField(max_length=40 ,null=True,blank=True)
      number = models.IntegerField(null=True,blank=True)
      myid = models.IntegerField(null=True,blank=True)
      situation = models.CharField(max_length=30 ,null=True,blank=True)
      
      def __str__(self):
         return (self.full_name +' ' + self.city)

class Email(models.Model):
   email=models.CharField(max_length=50)
   def __str__(self):
       return self.email


class Customer_infobycart(models.Model):
      full_name= models.CharField(max_length=30 ,null=True,blank=True)
      city = models.CharField(max_length=40 ,null=True,blank=True)
      number = models.IntegerField(null=True,blank=True)
      myid = models.CharField(max_length=100,null=True,blank=True)
      somme = models.CharField(max_length=100,null=True,blank=True)
      situation = models.CharField(max_length=30 ,null=True,blank=True)
      
      def __str__(self):
         return (self.full_name +' ' + self.city)

products/forms.py
from django.forms import ModelForm
from products.models import *
from django import forms
from django.views import *

class CustomerForm(ModelForm):
    class Meta:
        model = Customer_info
        fields = ("quantity","full_name","city","number")
        widgets = {
            'quantity':forms.NumberInput(attrs={
            "placeholder":"ادخل الكمية المرغوبة",
            "class":"form-control",
            "required":True,
            }),
            'full_name':forms.TextInput(attrs={
            "placeholder":"ادخل اسم الكامل",
            "class":"form-control",
            "required":True,
            }),
            'city':forms.TextInput(attrs={
            "placeholder":"ادخل المدينة",
            "class":"form-control",
            "required":True,
            }),
            'number':forms.NumberInput(attrs={
            "placeholder":"ادخل رقم الهاتف",
            "class":"form-control",
            "required":True,
            }),
            
                }
        
class CustomerbycartForm(ModelForm):
    class Meta:
        model = Customer_infobycart
        fields = ("full_name","city","number")
        widgets = {
            'full_name':forms.TextInput(attrs={
            "onkeyup":"getids()",   
            "placeholder":"ادخل اسم الكامل",
            "class":"form-control",
            "required":True,
            }),
            'city':forms.TextInput(attrs={
            "placeholder":"ادخل المدينة",
            "onkeyup":"sommeup()", 
            "class":"form-control",
            "required":True,
            }),
            'number':forms.NumberInput(attrs={
            "placeholder":"ادخل رقم الهاتف",
            "class":"form-control",
            "required":True,
            }),
            
                }        

products/views.py
from django.shortcuts import render,redirect
from products.models import Products,Customer_info,Email,Customer_infobycart
from products.forms import *
import json

def index(request):
    if request.method == 'POST':
        email=request.POST.get('email')
        data=Email(email=email)
        data.save() 
        return redirect('/done_email')   
    return render(request, 'index.html', {'pro' : Products.objects.all()})


def doneemail(request):
    return render(request, 'done_email.html')


def done(request):
    return render(request, 'done_demande.html', {'done':'done'})

def product_detial(request , id):
    product_detail=Products.objects.get(id=id)
    customer = CustomerForm()
    if request.method == 'POST':
        quantity=request.POST.get('quantity')
        full_name=request.POST.get('full_name')
        city=request.POST.get('city')
        number=request.POST.get('number')
       
        myid = request.POST.get('id')
        id_customer=Customer_info(myid=myid,quantity=quantity,full_name=full_name,city=city,number=number)
        
        id_customer.save()
        return redirect('/done')
        
    return render(request, 'products_details.html',{'prod':product_detail,'customer':customer , 'pro':Products.objects.all()})

def shoes(request):
    if request.method == 'POST':
        email=request.POST.get('email')
        data=Email(email=email)
        data.save() 
        return redirect('/done_email') 
    return render(request,'shoes.html' , {'pro':Products.objects.all()})

def tshirt(request):
    if request.method == 'POST':
        email=request.POST.get('email')
        data=Email(email=email)
        data.save() 
        return redirect('/done_email') 
    return   render(request,'tshirt.html',{'pro':Products.objects.all()})

def pants(request):
    if request.method == 'POST':
        email=request.POST.get('email')
        data=Email(email=email)
        data.save() 
        return redirect('/done_email') 
    return render(request,'pants.html',{'pro':Products.objects.all()}) 


def product_detialbycart(request):
    customerbycart = CustomerbycartForm()
    if request.method == 'POST':
        full_name=request.POST.get('full_name')
        city=request.POST.get('city')
        number=request.POST.get('number')
        myid = request.POST.get('myid')
        somme=request.POST.get('somme')
        id_customerbycart=Customer_infobycart(myid=myid,full_name=full_name,city=city,number=number,somme=somme)
        
        id_customerbycart.save()
        return redirect('/done')
        
    return render(request, 'cartinfo.html',{ 'customerbycart':customerbycart ,'pro':Products.objects.all()})

def productcart(request):
    
    return render(request,'productcart.html',{'pro':Products.objects.all()})     

templates/pants.html
{% load static %}
<!doctype html>
<html lang="ar" >
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title> ObouStore</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'product:Home' %}"><img class="logo" src="{% static 'img/logo.jpeg' %}"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'product:Home' %}">الرئسية <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  الفئة
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{%url 'product:tshirt'%}">القمصان</a>
                  <a class="dropdown-item" href="{%url 'product:pants'%}">السراويل</a>
                  <a class="dropdown-item" href="{%url 'product:shoes'%}">أحذية</a>
                  
                </div>
              </li>
           
          </ul>  
        </div>
      </nav>
      
     
      
       <div class="mycarousel" >
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img class="d-block w-100 myfirstimg" src="{%static 'img/thefirst.jpeg'%}" alt="First slide">
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100 myfirstimg" src="{%static 'img/thesecond.jpeg'%}" alt="Second slide">
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100" src="{% static 'img/thelast.jpeg'%}" alt="Third slide">
                  </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
          </div>

  <!--
         <div class="dropattention">
      <div class="drop2">
        <span><img src="{%static 'img/attention.png'%}" > ATTENTION:</span> THIS STORE IS A DROPSHIPING STORE
      </div>
    </div>
    -->
    <div  class="shopping"><a href="{%url 'product:productcart'%}">
      <img class="shoppingimg" src="{%static 'img/cart.png'%}" >
      <p id="shoppingnumbre">0</p></a>
    </div>
  

        
     <div class="testcenter">
      <div class="container">
        
            <div class="row center-row">
           
                 {%for product in pro %}
                   {%if product.categorie == "pants" %}
                   <div class=" mr-2 mt-5">
                    <div class="card" >
                      {%if product.image%}
                     <a href="{%url 'product:products_details' product.id%}"><img class="productimg card-img-top imgcard" src="{{product.image.url}}" alt="Card image cap"></a>
                       

                      {% endif%}
                      <div class="card-body">

                         <h5 class="card-title">{{product.price}} DH <span class="notprice">{{product.notprice}} DH</span> </h5>
                          <p class="card-text">Made in {{product.made}} </p> 
                          <p class="card-text">{{product.size}} </p> 
                          
                          <div class="lechoix">
                            <button  onclick="numbreofproduct()" data-product={{product.id}} data-img="{{product.image.url}}" data-categoru="{{product.categorie}}" data-price="{{product.price}}" class="categoryclick btn btn-outline-primary update-cart">اضافة الى السلة</button>
                            <a href="{%url 'product:products_details' product.id%}" class="categoryclick btn btn-outline-primary">مشاهدة</a>
                        </div> </div>
                      </div>
                 </div>
                 {%endif%}
          
                 {% endfor%}
                
                 </div>
            </div>    
                 
            </div>
            <div class="secondtitle">Obou Store</div>
     <div class="last">
      <div class="lasttitle"><div>ابق على تواصل معنا </div>
        <p>أحصل على إشعارات بأحدث المنتجات مباشرة في بريدك الالكتروني</p>
      </div>

      <form method="post" class="email">
        {% csrf_token %}
        <div class="form-group">
   
          <input type="email" required class="form-control mr-5" aria-describedby="emailHelp" name="email" placeholder="ادخل البريد الالكتروني ">
        </div>
        
        
        <button type="submit" class="btn btn-primary ml-5 mr-5">Submit</button>
      </form>
     </div>   



 <style>
   .lechoix{
    display: flex;
    justify-content: space-between;
  }
   nav ul li a{
    position: relative!important;
 }
 nav ul li a::before{
    content: "";
    width: 0;
    left: 0;
    height: 3px;
    position: absolute!important;
    bottom: 3px;
    background-color: blue;
    transition: all 0.5s ease;
 }
 nav ul li a:hover::before{
    width: 100%!important;
 }

 .card{
                transition: all ease 0.55s;
              }
  .card:hover{
                transform:translateY(-10px) ;
              }
              
  .email{
                display: flex;
                
                flex-direction: column;
                justify-content: center;
              }
  .secondtitle{
                background-color: rgb(189, 187, 187) ;
                padding: 10px;
                text-align: center;
              }
              .last{
                background: rgb(197, 197, 197);
                padding: 10px 0;
              }
              .lasttitle div{
                text-align: center;
                font-size: 25px;
                font-family: italic;
              }
              .lasttitle p{
                font-size: 13px;
                text-align: center;
              }

           .dropattention div span{
            color: red;
            }
            .dropattention div span img{
              width: 30px;
              
            }
            .dropattention{
              font-size: 20px;
              margin: 10px;
              display: flex;
              justify-content: center;
              justify-items: center;
              border: 3px solid black;

            }
              .notprice{
          font-size: medium!important;
          color: red!important;
          text-decoration: line-through!important;
      }
             .imgcard{
              height: 286px;
              
             }
             nav ul li a{
    position: relative!important;
 }
 nav ul li a::before{
    content: "";
    width: 0;
    left: 0;
    height: 3px;
    position: absolute!important;
    bottom: 3px;
    background-color: blue;
    transition: all 0.5s ease;
 }
 nav ul li a:hover::before{
    width: 100%!important;
 }
 nav{
  background-color: #232F3E;
 }
 .logo{
  width: 70px;
  height: 40px;
 }
     
 .categoryclick{
  display: flex;
  justify-content: center;
 }
 .shopping a{
              display: flex;
              position: fixed;
              right: 15px;
              top: 40px;
              z-index: 1;
             }
            .shopping a img{
              width: 40px;
              height: auto;
            }
            .shopping a p{
              background-color: red;
              color: aliceblue;
              font-size: large;
              padding: 1px;
              border-radius: 10px;
            }
            .lechoix{
             display: flex;
             justify-content: space-between;
              }
              .productimg{
              aspect-ratio: 2/2!important;
              object-fit: contain!important;
             }

             </style>   
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'js/card.js'%}"></script>
  
  </body>
</html>

templates/shoes.html
{% load static %}
<!doctype html>
<html lang="ar" >
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>ObouStore</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'product:Home' %}"><img class="logo" src="{% static 'img/logo.jpeg' %}"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'product:Home' %}">الرئسية <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                الفئة
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{%url 'product:tshirt'%}">القمصان</a>
                <a class="dropdown-item" href="{%url 'product:pants'%}">السراويل</a>
                <a class="dropdown-item" href="{%url 'product:shoes'%}">أحذية</a>
                
              </div>
            </li>
          </ul>  
        </div>
      </nav>
      
     
      
       <div class="mycarousel" >
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img class="d-block w-100 myfirstimg" src="{%static 'img/thefirst.jpeg'%}" alt="First slide">
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100 myfirstimg" src="{%static 'img/thesecond.jpeg'%}" alt="Second slide">
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100" src="{% static 'img/thelast.jpeg'%}" alt="Third slide">
                  </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
          </div>

  <!--
         <div class="dropattention">
      <div class="drop2">
        <span><img src="{%static 'img/attention.png'%}" > ATTENTION:</span> THIS STORE IS A DROPSHIPING STORE
      </div>
    </div>
    -->
    <div  class="shopping"><a href="{%url 'product:productcart'%}">
      <img class="shoppingimg" src="{%static 'img/cart.png'%}" >
      <p id="shoppingnumbre">0</p></a>
    </div>
  

        
     <div class="testcenter">
      <div class="container">
        
            <div class="row center-row">
            
                 {%for product in pro %}
                     {%if product.categorie == "shoes" %}
                 <div class=" mr-2 mt-5">
                    <div class="card" >
                      {%if product.image%}
                       <a href="{%url 'product:products_details' product.id%}"><img class="productimg card-img-top imgcard" src="{{product.image.url}}" alt="Card image cap"></a>
                    

                      {% endif%}
                      <div class="card-body">

                         <h5 class="card-title">{{product.price}} DH <span class="notprice">{{product.notprice}} DH</span> </h5>
                          <p class="card-text">Made in {{product.made}} </p> 
                          <p class="card-text"> {{product.size}} </p> 
                          
                          <div class="lechoix">
                            <button  onclick="numbreofproduct()" data-product={{product.id}} data-img="{{product.image.url}}" data-categoru="{{product.categorie}}" data-price="{{product.price}}" class="categoryclick btn btn-outline-primary update-cart">اضافة الى السلة</button>
                            <a href="{%url 'product:products_details' product.id%}" class="categoryclick btn btn-outline-primary">مشاهدة</a>
                        </div> </div>
                      </div>
                 </div>
                   {%endif%}
                 {% endfor%}
                
                 </div>
            </div>    
                 
            </div>
            <div class="secondtitle">Obou Store</div>
     <div class="last">
      <div class="lasttitle"><div>ابق على تواصل معنا </div>
        <p>أحصل على إشعارات بأحدث المنتجات مباشرة في بريدك الالكتروني</p>
      </div>

      <form method="post" class="email">
        {% csrf_token %}
        <div class="form-group">
   
          <input type="email" required class="form-control mr-5" aria-describedby="emailHelp" name="email" placeholder="ادخل البريد الالكتروني ">
        </div>
        
        
        <button type="submit" class="btn btn-primary ml-5 mr-5">Submit</button>
      </form>
     </div>   




            <style>
               .lechoix{
                  display: flex;
                  justify-content: space-between;
                 }
               .card{
                transition: all ease 0.55s;
              }
              .card:hover{
                transform:translateY(-10px) ;
              }
              
              .email{
                display: flex;
                
                flex-direction: column;
                justify-content: center;
              }
              .productimg{
              aspect-ratio: 2/2!important;
              object-fit: contain!important;
             }
              .secondtitle{
                background-color: rgb(189, 187, 187) ;
                padding: 10px;
                text-align: center;
              }
              .last{
                background: rgb(197, 197, 197);
                padding: 10px 0;
              }
              .lasttitle div{
                text-align: center;
                font-size: 25px;
                font-family: italic;
              }
              .lasttitle p{
                font-size: 13px;
                text-align: center;
              }

           .dropattention div span{
            color: red;
            }
            .dropattention div span img{
              width: 30px;
              
            }
            .dropattention{
              font-size: 20px;
              margin: 10px;
              display: flex;
              justify-content: center;
              justify-items: center;
              border: 3px solid black;

            }
              .notprice{
          font-size: medium!important;
          color: red!important;
          text-decoration: line-through!important;
      }
             .imgcard{
              height: 286px;
              
             }
             nav ul li a{
    position: relative!important;
 }
 nav ul li a::before{
    content: "";
    width: 0;
    left: 0;
    height: 3px;
    position: absolute!important;
    bottom: 3px;
    background-color: blue;
    transition: all 0.5s ease;
 }
 nav ul li a:hover::before{
    width: 100%!important;
 }
 nav{
  background-color: #232F3E;
 }
 .logo{
  width: 70px;
  height: 40px;
 }
 .categoryclick{
  display: flex;
  justify-content: center;
 }
 .shopping a{
              display: flex;
              position: fixed;
              right: 15px;
              top: 40px;
              z-index: 1;
             }
            .shopping a img{
              width: 40px;
              height: auto;
            }
            .shopping a p{
              background-color: red;
              color: aliceblue;
              font-size: large;
              padding: 1px;
              border-radius: 10px;
            }
            .lechoix{
    display: flex;
    justify-content: space-between;
  }
             

             </style>   
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'js/card.js'%}"></script>
  
  </body>
</html>